version: "3"
services:
  server:
    build: .
    depends_on:
      - postgres
    environment:
      #this variable would be managed with a docker secret
      DB_URL: postgresql://postgres:pwd@postgres:5432/parking
      LOCAL_PORT: 4000
      MAX_SPOTS_ALLOWED: 1500
      MIN_SPOTS_ALLOWED: 50
      JWT_SECRET: 52f29867439f77a04459002a4bc7ffb0df5fb3fea1a2e3deea9f1bc0a91e96c0
    ports:
      - "14000:4000"
    command: npm run start

  postgres:
    image: postgres:15.2
    user: postgres
    ports:
      - "15432:5432"
    environment:
      #this info would be managed with docker secrets
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pwd
      POSTGRES_DB: parking
